export type Language = 'en' | 'ru' | 'uz';

export const translations = {
  en: {
    logoTagline: "шедевры вкуса",
    nav: { about: "About", menu: "Menu", delivery: "Delivery", reviews: "Reviews", contact: "Contact", order: "Order Now" },
    hero: { subtitle: "Handmade with natural ingredients", title1: "Dessert Masterpieces", title2: "in Navoi", desc: "Experience the true taste of luxury. Every cheesecake is crafted with passion, precision, and the finest ingredients.", viewMenu: "View Menu", deliveryInfo: "Delivery Info" },
    about: { tag: "Our Story", title1: "Crafting", title2: "perfection", title3: " in every slice.", p1: "At CHEESEBAKE, we believe that a dessert is more than just a sweet treat—it is an experience, a moment of joy, and a masterpiece of flavor.", p2: "Every cheesecake we create is entirely handmade in our Navoi kitchen. We strictly refuse artificial additives, using only premium natural ingredients: rich cream cheese, fresh berries, Belgian chocolate, and pure butter.", p3: "Our mission is simple: to deliver the highest quality desserts that turn your ordinary days into celebrations.", promiseTitle: "\"Masterpieces of taste\"", promiseSub: "The Cheesebake Promise" },
    products: { tag: "Our Menu", title: "Signature Desserts", desc: "Explore our curated selection of handmade cheesecakes. Available whole for celebrations or by the slice for your daily indulgence.", items: [ { name: 'Classic New York', desc: 'Rich, creamy, and perfectly balanced with a buttery graham cracker crust.' }, { name: 'Wild Berry Bliss', desc: 'Topped with a vibrant compote of fresh seasonal berries.' }, { name: 'Chocolate Truffle', desc: 'Decadent dark Belgian chocolate blended into our signature cheese filling.' }, { name: 'Caramel Pecan', desc: 'Swirled with salted caramel and topped with candied pecans.' } ] },
    delivery: { tag: "Premium Service", title: "Fresh desserts delivered to your door.", desc: "We understand that cravings don't wait. Our dedicated delivery team ensures your cheesecakes arrive in perfect condition, maintaining their ideal temperature and beautiful presentation.", f1Title: "Fast Delivery (60–120 min)", f1Desc: "Get your desserts quickly within Navoi. Perfect for sudden guests or immediate cravings.", f2Title: "Wide Coverage Zone", f2Desc: "We deliver across all major districts of Navoi. Check with our manager for exact delivery costs to your area.", f3Title: "Safe Packaging", f3Desc: "Every dessert is packed in premium, temperature-controlled boxes to ensure it arrives looking and tasting flawless." },
    howToOrder: { title: "How to Order", desc: "Simple steps to get your dessert.", s1Title: "Choose Dessert", s1Desc: "Browse our menu and select your favorite cheesecake or dessert.", s2Title: "Contact Us", s2Desc: "Message us on Telegram or call us to place your order and confirm details.", s3Title: "Enjoy", s3Desc: "Receive your fresh, beautifully packaged dessert at your door." },
    advantages: { a1Title: "Natural Ingredients", a1Desc: "No artificial flavors or preservatives. Only pure, high-quality components.", a2Title: "100% Handmade", a2Desc: "Crafted with love and attention to detail by our expert pastry chefs.", a3Title: "Fast Delivery", a3Desc: "Prompt delivery across Navoi to ensure your dessert arrives fresh.", a4Title: "Premium Taste", a4Desc: "A perfect balance of textures and flavors that redefine luxury desserts." },
    reviews: { tag: "Testimonials", title: "What Our Clients Say", r1: "The best cheesecake I've ever had in Navoi. The texture is incredibly smooth, and the delivery was right on time.", r2: "Ordered the Classic New York for a family dinner. Everyone was blown away by the quality. Truly a masterpiece.", r3: "Beautiful packaging and divine taste. You can really feel that they use premium ingredients. Highly recommend!" },
    contact: { title: "Ready to Order?", desc: "Contact us to place your order or if you have any questions.", phone: "Phone", telegram: "Telegram", instagram: "Instagram", hours: "Working Hours", hoursVal: "Mon-Sun: 10:00 - 22:00", btn: "Message on Telegram" },
    footer: { desc: "Premium handmade cheesecakes delivered fresh in Navoi. Experience the true taste of luxury.", rights: "All rights reserved.", designed: "Designed for premium taste." }
  },
  ru: {
    logoTagline: "шедевры вкуса",
    nav: { about: "О нас", menu: "Меню", delivery: "Доставка", reviews: "Отзывы", contact: "Контакты", order: "Заказать" },
    hero: { subtitle: "Ручная работа из натуральных ингредиентов", title1: "Десертные шедевры", title2: "в Навои", desc: "Почувствуйте истинный вкус роскоши. Каждый чизкейк создается с любовью, особым вниманием к деталям и из самых лучших ингредиентов.", viewMenu: "Смотреть меню", deliveryInfo: "О доставке" },
    about: { tag: "Наша история", title1: "Создаем", title2: "совершенство", title3: " в каждом кусочке.", p1: "В CHEESEBAKE мы верим, что десерт — это больше, чем просто сладкое угощение. Это эмоции, момент радости и настоящий шедевр вкуса.", p2: "Каждый наш чизкейк полностью изготавливается вручную на нашей кухне в Навои. Мы категорически против искусственных добавок и используем только премиальные натуральные ингредиенты: настоящий сливочный сыр, свежие ягоды, бельгийский шоколад и натуральное сливочное масло.", p3: "Наша миссия проста: доставлять десерты высочайшего качества, которые превращают ваши обычные дни в праздники.", promiseTitle: "\"Шедевры вкуса\"", promiseSub: "Обещание Cheesebake" },
    products: { tag: "Наше меню", title: "Фирменные десерты", desc: "Изучите наш выбор чизкейков ручной работы. Доступны целиком для праздников или кусочками для ежедневного удовольствия.", items: [ { name: 'Классический Нью-Йорк', desc: 'Нежный, сливочный и идеально сбалансированный вкус с хрустящей песочной основой.' }, { name: 'Ягодное блаженство', desc: 'Украшен ярким конфи из свежих сезонных ягод.' }, { name: 'Шоколадный трюфель', desc: 'Изысканный темный бельгийский шоколад, гармонично сочетающийся с нашей фирменной сырной начинкой.' }, { name: 'Карамельный пекан', desc: 'С добавлением соленой карамели и карамелизированным пеканом.' } ] },
    delivery: { tag: "Премиум сервис", title: "Свежие десерты с доставкой до двери.", desc: "Мы понимаем, что настоящее удовольствие не должно ждать. Наша служба доставки гарантирует, что ваши чизкейки прибудут в идеальном состоянии, сохранив нужную температуру и безупречный внешний вид.", f1Title: "Быстрая доставка (60–120 мин)", f1Desc: "Получите ваши десерты быстро в любой точке Навои. Идеально для внезапных гостей или когда хочется сладкого прямо сейчас.", f2Title: "Широкая зона покрытия", f2Desc: "Мы доставляем во все основные районы Навои. Уточните у менеджера точную стоимость доставки в ваш район.", f3Title: "Надежная упаковка", f3Desc: "Каждый десерт упакован в премиальные термобоксы, чтобы он прибыл безупречным на вид и вкус." },
    howToOrder: { title: "Как заказать", desc: "Простые шаги, чтобы получить ваш десерт.", s1Title: "Выберите десерт", s1Desc: "Изучите наше меню и выберите ваш любимый чизкейк или десерт.", s2Title: "Свяжитесь с нами", s2Desc: "Напишите нам в Telegram или позвоните, чтобы оформить заказ и подтвердить детали.", s3Title: "Наслаждайтесь", s3Desc: "Получите ваш свежий, красиво упакованный десерт у вашей двери." },
    advantages: { a1Title: "Натуральные ингредиенты", a1Desc: "Никаких искусственных ароматизаторов или консервантов. Только чистые, высококачественные компоненты.", a2Title: "100% ручная работа", a2Desc: "Создано с любовью и вниманием к деталям нашими опытными кондитерами.", a3Title: "Быстрая доставка", a3Desc: "Оперативная доставка по Навои, чтобы ваш десерт прибыл свежим.", a4Title: "Премиальный вкус", a4Desc: "Идеальный баланс текстур и вкусов, который задает новые стандарты премиальных десертов." },
    reviews: { tag: "Отзывы", title: "Что говорят наши клиенты", r1: "Лучший чизкейк, который я когда-либо пробовала в Навои. Текстура невероятно нежная, а доставка была точно вовремя.", r2: "Заказывали Классический Нью-Йорк на семейный ужин. Все были поражены качеством. Поистине шедевр.", r3: "Красивая упаковка и божественный вкус. Действительно чувствуется, что используют премиальные ингредиенты. Очень рекомендую!" },
    contact: { title: "Готовы заказать?", desc: "Свяжитесь с нами для оформления заказа или если у вас есть вопросы.", phone: "Телефон", telegram: "Telegram", instagram: "Instagram", hours: "Часы работы", hoursVal: "Пн-Вс: 10:00 - 22:00", btn: "Написать в Telegram" },
    footer: { desc: "Премиальные чизкейки ручной работы с доставкой в Навои. Почувствуйте истинный вкус роскоши.", rights: "Все права защищены.", designed: "Создано для премиального вкуса." }
  },
  uz: {
    logoTagline: "шедевры вкуса",
    nav: { about: "Biz haqimizda", menu: "Menyu", delivery: "Yetkazib berish", reviews: "Mijozlar fikri", contact: "Aloqa", order: "Buyurtma berish" },
    hero: { subtitle: "Tabiiy masalliqlardan qo'lda tayyorlangan", title1: "Desert durdonalari", title2: "Navoiyda", desc: "Haqiqiy hashamat ta'mini his eting. Har bir chizkeyk mehr, e'tibor va eng sara masalliqlar bilan tayyorlanadi.", viewMenu: "Menyuni ko'rish", deliveryInfo: "Yetkazib berish" },
    about: { tag: "Bizning tariximiz", title1: "Har bir bo'lakda", title2: "mukammallik", title3: " yaratamiz.", p1: "CHEESEBAKE'da biz desert shunchaki shirinlik emas, balki quvonch lahzasi va ta'm durdonasi ekanligiga ishonamiz.", p2: "Biz yaratgan har bir chizkeyk Navoiydagi oshxonamizda to'liq qo'lda tayyorlanadi. Biz sun'iy qo'shimchalardan qat'iyan voz kechamiz, faqat yuqori sifatli tabiiy masalliqlardan foydalanamiz: haqiqiy qaymoqli pishloq, yangi rezavorlar, Belgiya shokoladi va toza sariyog'.", p3: "Maqsadimiz oddiy: oddiy kunlaringizni bayramga aylantiruvchi eng oliy sifatli shirinliklarni yetkazib berish.", promiseTitle: "\"Ta'm durdonalari\"", promiseSub: "Cheesebake va'dasi" },
    products: { tag: "Bizning menyu", title: "Maxsus shirinliklarimiz", desc: "Qo'lda tayyorlangan chizkeyklarimiz bilan tanishing. Bayramlar uchun butun holda yoki o'zingizni xursand qilish uchun bo'laklab buyurtma berishingiz mumkin.", items: [ { name: 'Klassik Nyu-York', desc: 'Mayin, qaymoqli va sariyog\'li kreker asosi bilan mukammal uyg\'unlashgan.' }, { name: 'Rezavorlar rohati', desc: 'Ustiga yangi mavsumiy rezavorlardan tayyorlangan qiyom solingan.' }, { name: 'Shokoladli tryufel', desc: 'Maxsus pishloqli asosimizga qorishilgan haqiqiy qora Belgiya shokoladi.' }, { name: 'Karamelli pekan', desc: 'Tuzli karamel va qovurilgan pekan yong\'oqlari bilan bezatilgan.' } ] },
    delivery: { tag: "Premium xizmat", title: "Yangi shirinliklar eshigingizgacha yetkazib beriladi.", desc: "Shirinlikka bo'lgan ishtiyoq kutib turolmasligini tushunamiz. Kuryerlarimiz chizkeyklaringizni ideal haroratda va chiroyli ko'rinishini saqlagan holda, mukammal holatda yetkazib berishadi.", f1Title: "Tez yetkazib berish (60–120 daqiqa)", f1Desc: "Shirinliklaringizni Navoiy bo'ylab tezda qabul qilib oling. Kutilmagan mehmonlar tashrifi yoki shirinlik xohlab qolganingizda ayni muddao.", f2Title: "Keng qamrov hududi", f2Desc: "Biz Navoiyning barcha tumanlariga yetkazib beramiz. Manzilingizga yetkazib berish narxini menejerimizdan aniqlashtirishingiz mumkin.", f3Title: "Ishonchli qadoqlash", f3Desc: "Har bir shirinlik o'zining mukammal ko'rinishi va ta'mini saqlab qolishi uchun maxsus haroratni saqlaydigan premium qutilarga qadoqlanadi." },
    howToOrder: { title: "Qanday buyurtma berish", desc: "Desertingizni olish uchun oddiy qadamlar.", s1Title: "Desertni tanlang", s1Desc: "Menyumizni ko'rib chiqing va sevimli chizkeyk yoki desertingizni tanlang.", s2Title: "Biz bilan bog'laning", s2Desc: "Buyurtma berish va tafsilotlarni tasdiqlash uchun bizga Telegram'da yozing yoki qo'ng'iroq qiling.", s3Title: "Bahramand bo'ling", s3Desc: "Yangi, chiroyli qadoqlangan desertingizni eshickingizda qabul qiling." },
    advantages: { a1Title: "Tabiiy masalliqlar", a1Desc: "Hech qanday sun'iy qo'shimchalar va konservantlarsiz. Faqat toza, yuqori sifatli masalliqlar.", a2Title: "100% qo'l mehnati", a2Desc: "Tajribali qandolatchilarimiz tomonidan mehr va katta e'tibor bilan tayyorlanadi.", a3Title: "Tez yetkazib berish", a3Desc: "Shirinligingiz yangi holatda yetib borishini ta'minlash uchun Navoiy bo'ylab tezkor yetkazib berish xizmati.", a4Title: "Premium ta'm", a4Desc: "Hashamatli shirinliklar qanday bo'lishi kerakligini ko'rsatib beruvchi tekstura va ta'mlarning mukammal uyg'unligi." },
    reviews: { tag: "Mijozlar fikri", title: "Mijozlarimizning fikrlari", r1: "Navoiyda yegan eng zo'r chizkeykim. Teksturasi juda ham mayin va o'z vaqtida yetkazib berishdi.", r2: "Oilaviy kechki ovqat uchun Klassik Nyu-York buyurtma qildik. Sifatidan hamma lol qoldi. Haqiqiy durdona.", r3: "Chiroyli qadoq va ajoyib ta'm. Haqiqatan ham sifatli masalliqlardan tayyorlanganligi bilinib turibdi. Barchaga tavsiya qilaman!" },
    contact: { title: "Buyurtma berishga tayyormisiz?", desc: "Buyurtma berish yoki savollaringiz bo'lsa, biz bilan bog'laning.", phone: "Telefon", telegram: "Telegram", instagram: "Instagram", hours: "Ish vaqti", hoursVal: "Dush-Yaksh: 10:00 - 22:00", btn: "Telegram orqali yozish" },
    footer: { desc: "Navoiy bo'ylab yetkazib beriladigan, qo'lda tayyorlangan premium chizkeyklar. Haqiqiy hashamat ta'mini his eting.", rights: "Barcha huquqlar himoyalangan.", designed: "Premium ta'm uchun yaratilgan." }
  }
};
